import type { ProgressFormulaConfig, ProgressSignalInput } from './types';

export const progressFormulaConfig: ProgressFormulaConfig = {
  targetAccuracy: 75,
  targetMastery: 80,
  targetResponseSeconds: 75,
  strongMastery: 84,
  recentPracticeDays: 4,
  stalePracticeDays: 14,
  refreshSoonHours: 36,
  weights: {
    masteryGap: 0.72,
    recentAccuracyGap: 0.82,
    questionTypeGap: 0.36,
    recentErrors: 4.2,
    stalePractice: 0.92,
    recentlyTestedLowAccuracy: 11,
    incompleteContent: 4.6,
    responseTime: 0.18,
    vocabularyDue: 1.1,
    grammarGap: 0.56,
    miniTestGap: 0.42,
    mockScoreGap: 0.46,
    examUrgency: 9,
    attemptConfidence: 5,
    strongRecentPenalty: 18,
    freePlanLockedPenalty: 12,
  },
  contextBoosts: {
    dashboard: {
      'focused-practice': 5,
      'vocabulary-review': 4,
      'grammar-practice': 3,
      'watch-lesson': 2,
    },
    'my-learning': {
      'watch-lesson': 12,
      'focused-practice': 5,
      'grammar-practice': 3,
      'vocabulary-review': 3,
    },
    listening: {
      'focused-practice': 10,
      'review-mistakes': 8,
      'mini-test': 4,
      'watch-lesson': 4,
    },
    vocabulary: {
      'vocabulary-review': 12,
      'watch-lesson': 3,
    },
    grammar: {
      'grammar-practice': 12,
      'watch-lesson': 3,
    },
    progress: {
      'review-mistakes': 8,
      'focused-practice': 6,
      'mini-test': 5,
      'mock-test': 4,
      'writing-feedback-review': 4,
      'speaking-practice': 4,
    },
  },
};

export const progressSignalInputs: ProgressSignalInput[] = [
  {
    id: 'signal-listening-detail-academic-talk',
    skillSlug: 'listening',
    skillTitle: 'Listening',
    subskillSlug: 'detail',
    subskillTitle: 'Detail Questions',
    taskTypeSlug: 'academic-talk',
    taskTypeTitle: 'Academic Talk',
    topicSlug: 'campus-life',
    topicTitle: 'Campus Facilities',
    masteryScore: 68,
    recentAccuracy: 48,
    practiceAccuracy: 52,
    questionTypePerformance: 48,
    subskillMastery: 68,
    timeSpentMinutes: 96,
    responseTimeSeconds: 91,
    lastPracticedAt: '2026-09-03T18:42:00.000Z',
    attemptCount: 7,
    recentErrors: 6,
    targetScore: 105,
    targetExamDate: '2026-10-20T09:00:00.000Z',
    incompleteContentCount: 1,
    status: 'active',
    sortOrder: 10,
    isPremium: false,
    recommendation: {
      type: 'focused-practice',
      title: 'Listening - Academic Talk',
      actionLabel: 'Start Focused Practice',
      actionHref: '/practice/listening?mode=practice&task=academic-talk&subskill=detail&difficulty=adaptive&length=standard',
      contentId: 'listening-detail-academic-talk-standard',
      estimatedMinutes: 20,
      expiresAt: '2026-09-07T23:59:00.000Z',
      visibleInContexts: ['dashboard', 'my-learning', 'listening', 'progress'],
    },
  },
  {
    id: 'signal-reading-inference-review',
    skillSlug: 'reading',
    skillTitle: 'Reading',
    subskillSlug: 'inference',
    subskillTitle: 'Inference',
    taskTypeSlug: 'reading-section',
    taskTypeTitle: 'Reading Section',
    topicSlug: 'environment',
    topicTitle: 'Urban Green Infrastructure',
    masteryScore: 63,
    recentAccuracy: 48,
    practiceAccuracy: 54,
    questionTypePerformance: 48,
    subskillMastery: 63,
    timeSpentMinutes: 86,
    responseTimeSeconds: 104,
    lastPracticedAt: '2026-09-03T10:20:00.000Z',
    attemptCount: 8,
    recentErrors: 7,
    miniTestScore: 61,
    mockTestScore: 94,
    targetScore: 105,
    targetExamDate: '2026-10-20T09:00:00.000Z',
    incompleteContentCount: 2,
    status: 'active',
    sortOrder: 20,
    isPremium: false,
    recommendation: {
      type: 'review-mistakes',
      title: 'Reading - Inference Review',
      actionLabel: 'Review Mistakes',
      actionHref: '/practice/reading?subskill=inference&mode=review',
      contentId: 'reading-inference-mistake-review',
      estimatedMinutes: 18,
      expiresAt: '2026-09-07T23:59:00.000Z',
      visibleInContexts: ['dashboard', 'progress'],
    },
  },
  {
    id: 'signal-vocabulary-review-due',
    skillSlug: 'vocabulary',
    skillTitle: 'Vocabulary',
    subskillSlug: 'academic-collocations',
    subskillTitle: 'Academic Collocations',
    taskTypeSlug: 'spaced-review',
    taskTypeTitle: 'Spaced Review',
    topicSlug: 'academic-core',
    topicTitle: 'Academic Core',
    masteryScore: 71,
    recentAccuracy: 64,
    practiceAccuracy: 66,
    questionTypePerformance: 62,
    subskillMastery: 71,
    timeSpentMinutes: 42,
    responseTimeSeconds: 63,
    lastPracticedAt: '2026-09-02T17:30:00.000Z',
    attemptCount: 11,
    recentErrors: 4,
    vocabularyReviewState: { dueCount: 24, weakCount: 7, savedDueCount: 5, state: 'due' },
    targetScore: 105,
    targetExamDate: '2026-10-20T09:00:00.000Z',
    incompleteContentCount: 0,
    status: 'active',
    sortOrder: 30,
    isPremium: false,
    recommendation: {
      type: 'vocabulary-review',
      title: 'Vocabulary Review - Academic Core',
      actionLabel: 'Review Due Words',
      actionHref: '/vocabulary',
      contentId: 'vocab-set-academic-core',
      estimatedMinutes: 12,
      expiresAt: '2026-09-06T23:59:00.000Z',
      visibleInContexts: ['dashboard', 'my-learning', 'vocabulary', 'progress'],
    },
  },
  {
    id: 'signal-grammar-relative-clauses',
    skillSlug: 'grammar',
    skillTitle: 'Grammar',
    subskillSlug: 'relative-clauses',
    subskillTitle: 'Relative Clauses',
    taskTypeSlug: 'guided-practice',
    taskTypeTitle: 'Guided Practice',
    topicSlug: 'clauses',
    topicTitle: 'Clauses',
    masteryScore: 61,
    recentAccuracy: 58,
    practiceAccuracy: 60,
    questionTypePerformance: 56,
    subskillMastery: 61,
    timeSpentMinutes: 38,
    responseTimeSeconds: 78,
    lastPracticedAt: '2026-08-31T12:10:00.000Z',
    attemptCount: 5,
    recentErrors: 5,
    grammarMastery: 61,
    targetScore: 105,
    targetExamDate: '2026-10-20T09:00:00.000Z',
    incompleteContentCount: 1,
    status: 'active',
    sortOrder: 40,
    isPremium: false,
    recommendation: {
      type: 'grammar-practice',
      title: 'Grammar Practice - Relative Clauses',
      actionLabel: 'Practice Grammar',
      actionHref: '/grammar/relative-clauses',
      contentId: 'grammar-topic-relative-clauses',
      estimatedMinutes: 15,
      expiresAt: '2026-09-08T23:59:00.000Z',
      visibleInContexts: ['dashboard', 'my-learning', 'grammar', 'progress'],
    },
  },
  {
    id: 'signal-writing-feedback-review',
    skillSlug: 'writing',
    skillTitle: 'Writing',
    subskillSlug: 'coherence',
    subskillTitle: 'Coherence',
    taskTypeSlug: 'integrated-writing',
    taskTypeTitle: 'Integrated Writing',
    topicSlug: 'transportation',
    topicTitle: 'Remote Work and Transportation',
    masteryScore: 68,
    recentAccuracy: 62,
    practiceAccuracy: 64,
    questionTypePerformance: 60,
    subskillMastery: 68,
    timeSpentMinutes: 72,
    responseTimeSeconds: 0,
    lastPracticedAt: '2026-09-01T20:10:00.000Z',
    attemptCount: 4,
    recentErrors: 4,
    targetScore: 105,
    targetExamDate: '2026-10-20T09:00:00.000Z',
    incompleteContentCount: 1,
    status: 'active',
    sortOrder: 50,
    isPremium: false,
    recommendation: {
      type: 'writing-feedback-review',
      title: 'Writing Feedback Review',
      actionLabel: 'Review Feedback',
      actionHref: '/practice/writing',
      contentId: 'writing-feedback-integrated-04',
      estimatedMinutes: 16,
      expiresAt: '2026-09-08T23:59:00.000Z',
      visibleInContexts: ['dashboard', 'progress'],
    },
  },
  {
    id: 'signal-speaking-fluency-practice',
    skillSlug: 'speaking',
    skillTitle: 'Speaking',
    subskillSlug: 'fluency',
    subskillTitle: 'Fluency',
    taskTypeSlug: 'independent-speaking',
    taskTypeTitle: 'Independent Speaking',
    topicSlug: 'campus-life',
    topicTitle: 'Role Models',
    masteryScore: 61,
    recentAccuracy: 58,
    practiceAccuracy: 57,
    questionTypePerformance: 55,
    subskillMastery: 61,
    timeSpentMinutes: 44,
    responseTimeSeconds: 120,
    lastPracticedAt: '2026-08-29T19:45:00.000Z',
    attemptCount: 3,
    recentErrors: 4,
    targetScore: 105,
    targetExamDate: '2026-10-20T09:00:00.000Z',
    incompleteContentCount: 1,
    status: 'active',
    sortOrder: 60,
    isPremium: false,
    recommendation: {
      type: 'speaking-practice',
      title: 'Speaking Practice - Fluency',
      actionLabel: 'Start Speaking',
      actionHref: '/practice/speaking',
      contentId: 'speaking-independent-fluency-task-02',
      estimatedMinutes: 14,
      expiresAt: '2026-09-08T23:59:00.000Z',
      visibleInContexts: ['dashboard', 'progress'],
    },
  },
  {
    id: 'signal-watch-listening-strategy-video',
    skillSlug: 'listening',
    skillTitle: 'Listening',
    subskillSlug: 'note-taking',
    subskillTitle: 'Note Taking',
    taskTypeSlug: 'academic-talk',
    taskTypeTitle: 'Academic Talk',
    topicSlug: 'campus-life',
    topicTitle: 'Lecture Notes',
    masteryScore: 70,
    recentAccuracy: 66,
    practiceAccuracy: 66,
    questionTypePerformance: 64,
    subskillMastery: 70,
    timeSpentMinutes: 64,
    responseTimeSeconds: 84,
    lastPracticedAt: '2026-09-02T21:15:00.000Z',
    attemptCount: 6,
    recentErrors: 5,
    targetScore: 105,
    targetExamDate: '2026-10-20T09:00:00.000Z',
    incompleteContentCount: 2,
    status: 'active',
    sortOrder: 70,
    isPremium: false,
    recommendation: {
      type: 'watch-lesson',
      title: 'Watch Lesson - Note Taking Strategy',
      actionLabel: 'Watch Lesson',
      actionHref: '/learning/videos/listening-note-map-lecture',
      contentId: 'listening-note-map-lecture',
      estimatedMinutes: 18,
      expiresAt: '2026-09-09T23:59:00.000Z',
      visibleInContexts: ['dashboard', 'my-learning', 'listening'],
    },
  },
  {
    id: 'signal-mini-test-reading-inference',
    skillSlug: 'reading',
    skillTitle: 'Reading',
    subskillSlug: 'inference',
    subskillTitle: 'Inference',
    taskTypeSlug: 'mini-test',
    taskTypeTitle: 'Mini Test',
    topicSlug: 'environment',
    topicTitle: 'Environment',
    masteryScore: 66,
    recentAccuracy: 63,
    practiceAccuracy: 63,
    questionTypePerformance: 61,
    subskillMastery: 66,
    timeSpentMinutes: 35,
    responseTimeSeconds: 96,
    lastPracticedAt: '2026-09-01T09:20:00.000Z',
    attemptCount: 5,
    recentErrors: 4,
    miniTestScore: 61,
    targetScore: 105,
    targetExamDate: '2026-10-20T09:00:00.000Z',
    incompleteContentCount: 0,
    status: 'active',
    sortOrder: 80,
    isPremium: false,
    recommendation: {
      type: 'mini-test',
      title: 'Mini Test - Reading Inference',
      actionLabel: 'Build Mini Test',
      actionHref: '/tests/mini?skill=reading&task=reading-section&subskill=inference&difficulty=adaptive&length=10&mode=practice',
      contentId: 'mini-test-reading-inference-adaptive',
      estimatedMinutes: 12,
      expiresAt: '2026-09-09T23:59:00.000Z',
      visibleInContexts: ['dashboard', 'progress'],
    },
  },
  {
    id: 'signal-mock-test-gap',
    skillSlug: 'test-strategy',
    skillTitle: 'Test Strategy',
    subskillSlug: 'full-mock-readiness',
    subskillTitle: 'Full Mock Readiness',
    taskTypeSlug: 'mock-test',
    taskTypeTitle: 'Mock Test',
    topicSlug: 'readiness',
    topicTitle: 'Readiness',
    masteryScore: 73,
    recentAccuracy: 70,
    practiceAccuracy: 70,
    questionTypePerformance: 70,
    subskillMastery: 73,
    timeSpentMinutes: 120,
    responseTimeSeconds: 0,
    lastPracticedAt: '2026-08-26T11:00:00.000Z',
    attemptCount: 2,
    recentErrors: 3,
    mockTestScore: 94,
    targetScore: 105,
    targetExamDate: '2026-10-20T09:00:00.000Z',
    incompleteContentCount: 0,
    status: 'active',
    sortOrder: 90,
    isPremium: true,
    recommendation: {
      type: 'mock-test',
      title: 'Mock Test - Target Gap Check',
      actionLabel: 'Take Mock Test',
      actionHref: '/tests/mock',
      contentId: 'mock-test-target-gap',
      estimatedMinutes: 120,
      requiredPlan: 'premium',
      isPremium: true,
      expiresAt: '2026-09-12T23:59:00.000Z',
      visibleInContexts: ['progress'],
    },
  },
  {
    id: 'signal-inactive-old-vocabulary',
    skillSlug: 'vocabulary',
    skillTitle: 'Vocabulary',
    subskillSlug: 'old-review',
    subskillTitle: 'Old Review',
    taskTypeSlug: 'spaced-review',
    taskTypeTitle: 'Spaced Review',
    masteryScore: 20,
    recentAccuracy: 20,
    practiceAccuracy: 20,
    questionTypePerformance: 20,
    subskillMastery: 20,
    timeSpentMinutes: 4,
    responseTimeSeconds: 140,
    lastPracticedAt: null,
    attemptCount: 1,
    recentErrors: 9,
    vocabularyReviewState: { dueCount: 99, weakCount: 42, savedDueCount: 7, state: 'due' },
    targetScore: 105,
    targetExamDate: '2026-10-20T09:00:00.000Z',
    incompleteContentCount: 3,
    status: 'inactive',
    sortOrder: 999,
    isPremium: false,
    recommendation: {
      type: 'vocabulary-review',
      title: 'Inactive Vocabulary Review',
      actionLabel: 'Review',
      actionHref: '/vocabulary',
      contentId: 'inactive-vocab-review',
      estimatedMinutes: 10,
      expiresAt: '2026-09-05T23:59:00.000Z',
      visibleInContexts: ['vocabulary'],
    },
  },
];
